# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HaCareem_Dexterous' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HaCareem_Dexterous
	pod 'GoogleMaps'
	pod 'Alamofire', '~> 4.4'
	pod 'SwiftyJSON'
	pod 'Kingfisher', '~> 3.0'
	pod 'IQKeyboardManagerSwift'
end
